version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    hostname: db
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - mentor-doc-db:/var/lib/mysql
  server:
    image: golang:1.12.7
    command: ["/bin/bash", "-c", "go get github.com/codegangsta/gin && cd /opt/server/packages/api && gin --appPort $API_PORT -i run main.go"]
    environment:
      - "API_PORT=${API_PORT}"
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./:/opt/server
    depends_on:
      - db
  website:
    image: node:10.13.0
    command: ["/bin/bash", "-c", "cd /opt/mentordoc && npm rebuild node-sass && cd /opt/mentordoc/packages/frontend-website && npm run start"]
    ports:
      - "9000:9000"
    volumes:
      - ${CURDIR}:/opt/mentordoc
volumes:
  mentor-doc-db: