version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    hostname: db
    environment:
      MYSQL_DATABASE: mentor_doc
      MYSQL_USER: userlocal
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mentor-doc-db:/var/lib/mysql
  server:
    image: golang:1.12.7
    command: ["/bin/bash", "-c", "go get github.com/codegangsta/gin && cd /opt/server/packages/api && gin --appPort 5050 -i run main.go"]
    environment:
      - "DATABASE_NAME=mentor_doc"
      - "DATABASE_USERNAME=userlocal"
      - "DATABASE_PASSWORD=password"
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=3306"
      - "MIGRATION_DIR=migrations"
      - "JWT_SIGNING_KEY=localjwtsigningkey"
      - "PORT=5050"
      - "HOST="
    ports:
      - "5050:5050"
    volumes:
      - ./:/opt/server
    depends_on:
      - db
volumes:
  mentor-doc-db: